### ISSUE TITLE
Data life cycle

### ISSUE THREAD

**Issue by ghost** [TomasS666/real-time-web-1920#8]
As discussed, you weren't able to create a data life cycle of your application. Because the complexity of your app it is helpful to have one.
Some data life cycles to help you understand how to create one and as inspiration:
- [DLC 1](https://github.com/qiubee/live-apps/blob/master/images/data-life-cycle-diagram.jpg)
- [DLC 2](https://github.com/follywolly/weatherworld/blob/master/docs/rt_diagram_week3_api.png)
- [DLC 3](https://github.com/chelseadoeleman/real-time-web-1819/blob/master/docs/data2.png)

**Comment by TomasStolp** [comment]
Thanks man! Made one in the meanwhile or well, even more than one. Need to refactor them before the deadline.
